edition = "2021"
newline_style = "Unix"

# maximum length of comments.
comment_width = 100
# break comments to fit on the line
wrap_comments = true
# convert `/* */` comments to `//` comments where possible
normalize_comments = true
# format code snippet included in doc comments.
format_code_in_doc_comments = true

# merge imports from the same module into a single use
# statement. Conversely, imports from different modules
# are split into separate statements.
imports_granularity = "Module"
# `type` and `const` are put first, then macros and methods.
reorder_impl_items = true
# space in braces like Page4Kb {index} -> Page4Kb { index }
spaces_within_braces = true
